Feature/type refactor
Graffle/flow-c-sharp-sdk pull request #14
Opened 2022-02-10 20:01 UTC by ben-graffle

Primary change here is refactoring of the following functions

* `FlowValueType CreateFromCadence(string type, string cadenceJsonValue)`
* `FlowValueType Create(string type, dynamic value)`

Added a bunch of missing unit tests as well

2022-02-11 19:28 UTC, ben-graffle commented on Graffle.FlowSdk/Types/Int64Type.cs
> +        public Int64Type(string value) : base(Int64.Parse(value))
found this bug with unit tests 💹

2022-02-14 17:49 UTC, dakota-graffle requested changes

2022-02-14 17:49 UTC, dakota-graffle commented on Graffle.FlowSdk/Types/FlowValueType.cs
> +            if (type == null)
string.IsNullOrWhiteSpace

2022-02-14 18:05 UTC, ben-graffle commented on Graffle.FlowSdk/Types/FlowValueType.cs
> +            if (type == null)
fixed with latest commit

2022-02-14 18:17 UTC, dakota-graffle approved these changes

2022-02-14 18:26 UTC, dakota-graffle approved these changes

2022-02-14 18:26 UTC, merged